import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Dummy from "../components/dummy"
export default function Home() {
  return (
    <div className={styles.container}>
    <Dummy/>
         {/* style jsx */}
        <style jsx>
           {`
           .bug {
            color:red;
           }
           `}
        </style>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
          <ul>
           <Link href='/'> <li>Home</li></Link>
           <Link href='/blog'> <li>Blog</li></Link>
           <Link href='/about'> <li>About Us</li></Link>
           <Link href='/contact'> <li>Contact Us</li></Link>
          </ul>
        </nav>
       
      <main className={styles.main}>
    
        <h2 className={styles.title}>
         <span className='bug dummy'> Bug founding place</span>
        </h2>
        <div className="blogs">
          <h3> How to learn ES6 for beginners</h3>
          <p>
           Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsa commodi eveniet, quia in modi consectetur iusto mollitia. Similique nihil necessitatibus minima omnis vel laboriosam laborum reprehenderit, vitae, illo inventore possimus ullam cumque magni obcaecati.
          </p>
          <h3>How to learn ES6 for Hustlers</h3>
          <p>
           Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsa commodi eveniet, quia in modi consectetur iusto mollitia. Similique nihil necessitatibus minima omnis vel laboriosam laborum reprehenderit, vitae, illo inventore possimus ullam cumque magni obcaecati.
          </p>
          <h3>How to learn ES6 for geniuses</h3>
          <p>
           Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsa commodi eveniet, quia in modi consectetur iusto mollitia. Similique nihil necessitatibus minima omnis vel laboriosam laborum reprehenderit, vitae, illo inventore possimus ullam cumque magni obcaecati.
          </p>
        </div>

        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
